sudo: required

language: php

php:
  - "7.2"

before_script:
  - sudo cp ServerConfig/sites-available.travis/* /etc/nginx/sites-available/
  - sudo ln -s /etc/nginx/sites-available/api.exosuite.conf /etc/nginx/sites-enabled/
  - sudo ln -s /etc/nginx/sites-available/exosuite.conf /etc/nginx/sites-enabled/
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo cat /etc/nginx/sites-enabled/exosuite.conf
  - sudo cat /etc/nginx/sites-enabled/api.exosuite.conf
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo service nginx restart
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - sudo service nginx status

script:
  - vendor/bin/phpunit --testsuite API
  - vendor/bin/phpunit --testsuite Unit
  - vendor/bin/phpunit --testsuite Feature

addons:
  hosts:
    - exosuite
    - exosuite.local
    - api.exosuite.local
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      - nginx