sudo: required

language: php

php:
  - "7.2"

env:
  global:
    - SITE_URL="http://exosuite.local"
    - SITE_DOMAIN="exosuite.local"
    - API_SITE_DOMAIN="api.exosuite.local"

before_script:
  - sudo cp ServerConfig/sites-available/* /etc/nginx/sites-available/
  - sudo ln -s /etc/nginx/sites-available/$SITE_DOMAIN /etc/nginx/sites-enabled/
  - sudo ln -s /etc/nginx/sites-available/$API_SITE_DOMAIN /etc/nginx/sites-enabled/
  - sudo rm /etc/nginx/sites-enabled/default
  - sudo rm  ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/*
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp  ServerConfig/pool.d/* ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/
  - sudo echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -e 's,listen.owner = www-data,listen.owner = ${travis.user},g' --in-place ~/.phpenv/versions/${phpenv_version_name}/etc/php-fpm.d/www.conf
  - sudo sed -e 's,listen.owner = www-data,listen.owner = ${travis.user},g' --in-place ~/.phpenv/versions/${phpenv_version_name}/etc/php-fpm.d/api.conf
  - sudo sed -e 's,listen.group = www-data,listen.group = ${travis.user},g' --in-place ~/.phpenv/versions/${phpenv_version_name}/etc/php-fpm.d/www.conf
  - sudo sed -e 's,listen.group = www-data,listen.group = ${travis.user},g' --in-place ~/.phpenv/versions/${phpenv_version_name}/etc/php-fpm.d/api.conf
  - sudo sed -e 's,owner = www-data,owner = ${travis.user},g' --in-place ~/.phpenv/versions/${phpenv_version_name}/etc/php-fpm.d/www.conf
  - sudo sed -e 's,owner = www-data,owner = ${travis.user},g' --in-place ~/.phpenv/versions/${phpenv_version_name}/etc/php-fpm.d/api.conf
  - sudo sed -e 's,group = www-data,group = ${travis.user},g' --in-place ~/.phpenv/versions/${phpenv_version_name}/etc/php-fpm.d/www.conf
  - sudo sed -e 's,group = www-data,group = ${travis.user},g' --in-place ~/.phpenv/versions/${phpenv_version_name}/etc/php-fpm.d/api.conf
  - sudo ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - sudo service php7.2-fpm restart
  - sudo service nginx restart

script:
  - vendor/bin/phpunit --testsuite API
  - vendor/bin/phpunit --testsuite Unit
  - vendor/bin/phpunit --testsuite Feature

addons:
  hosts:
    - exosuite.local
    - api.exosuite.local
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      - nginx