sudo: required

language: php

php:
  - "7.2"

env:
  global:
    - SITE_URL="http://exosuite.local"
    - SITE_DOMAIN="exosuite.local"
    - API_SITE_DOMAIN="api.exosuite.local"

install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update --no-install-recommends --force-yes
  - sudo apt-get install php7.2 php7.2-mbstring php7.2-xml php7.2-json php7.2-common php7.2-cli php7.2-fpm  --no-install-suggests --no-install-recommends --force-yes

before_script:
  - sudo sed -e "s,/mnt/hgfs/ExoSuiteAPI/public,$(pwd)/public,g" --in-place ServerConfig/sites-available/api.exosuite.conf
  - sudo sed -e "s,/mnt/hgfs/ExoSuiteAPI/public,$(pwd)/public,g" --in-place ServerConfig/sites-available/exosuite.conf
  - sudo cp ServerConfig/sites-available/* /etc/nginx/sites-available/
  - sudo ln -s /etc/nginx/sites-available/api.exosuite.conf /etc/nginx/sites-enabled/
  - sudo ln -s /etc/nginx/sites-available/exosuite.conf /etc/nginx/sites-enabled/
  - sudo rm -rf /etc/php/7.2/fpm/pool.d
  - sudo cp -r ServerConfig/pool.d /etc/php/7.2/fpm/
  - sudo cat /etc/nginx/sites-enabled/exosuite.conf
  - sudo cat /etc/nginx/sites-enabled/api.exosuite.conf
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - sudo service php7.2-fpm restart
  - sudo service nginx restart

script:
  - vendor/bin/phpunit --testsuite API
  - vendor/bin/phpunit --testsuite Unit
  - vendor/bin/phpunit --testsuite Feature

addons:
  hosts:
    - exosuite.local
    - api.exosuite.local
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      - nginx